from pathlib import Path

path = Path("app.js")
text = path.read_bytes()
old = b"  const openUserModal = () => qs('#user-modal')?.classList.remove('hidden');\r\n  const closeUserModal = () => {\r\n    const m = qs('#user-modal');\r\n    if (!m) return;\r\n    m.classList.add('hidden');\r\n    qs('#user-form')?.reset();\r\n    const msg = qs('#user-form-msg');\r\n    if (msg) msg.textContent = '';\r\n  };\r\n\r\n  qs('#add-user')?.addEventListener('click', openUserModal);\r\n  qs('#user-cancel')?.addEventListener('click', closeUserModal);\r\n  qs('#user-form')?.addEventListener('submit', (e) => {\r\n    e.preventDefault();\r\n    const name = qs('#user-name').value.trim();\r\n    const phone = qs('#user-phone').value.trim();\r\n    const msg = qs('#user-form-msg');\r\n    if (!name){ msg.textContent = 'Ù†Ø§Ù… Ø±Ø§ ÙˆØ§Ø±Ø¯ Ú©Ù†ÛŒØ¯.'; return; }\r\n    if (!/^\\d{11}$/.test(phone)) { msg.textContent = 'Ø´Ù…Ø§Ø±Ù‡ ØªÙ„ÙÙ† Ø¨Ø§ÛŒØ¯ Û±Û± Ø±Ù‚Ù… Ø¨Ø§Ø´Ø¯.'; return; }\r\n    const newUser = { name, phone, active: true };\r\n    USER_DB.push(newUser);\r\n    renderUsers();\r\n    updateKpis();\r\n    closeUserModal();\r\n    syncUserToBackend(newUser);\r\n  });\r\n"
new = b"  qs('#add-user')?.addEventListener('click', () => openUserModal('add'));\r\n  qs('#user-cancel')?.addEventListener('click', closeUserModal);\r\n  qs('#user-form')?.addEventListener('submit', async (e) => {\r\n    e.preventDefault();\r\n    const form = e.currentTarget;\r\n    const mode = form.dataset.mode || 'add';\r\n    const name = qs('#user-name').value.trim();\r\n    const phone = qs('#user-phone').value.trim();\r\n    const workId = qs('#user-work-id').value.trim();\r\n    const idNumber = qs('#user-id-number').value.trim();\r\n    const msg = qs('#user-form-msg');\r\n    if (!name){ setHintMessage(msg, 'نام را وارد کنید.', true); return; }\r\n    if (!/^\\d{11}$/.test(phone)) { setHintMessage(msg, 'شماره تلفن باید 11 رقم باشد.', true); return; }\r\n    if (mode === 'edit') {\r\n      const code = qs('#user-code').value.trim();\r\n      if (!code) { setHintMessage(msg, 'کد کاربر معتبر نیست.', true); return; }\r\n      try {\r\n        await updateUserOnServer({ code, name, phone, work_id: workId, id_number: idNumber });\r\n        await loadUserListFromDb();\r\n        closeUserModal();\r\n      } catch (err) {\r\n        setHintMessage(msg, err.message || 'خطا در به‌روزرسانی کاربر.', true);\r\n      }\r\n      return;\r\n    }\r\n    const newUser = { name, phone, active: true };\r\n    USER_DB.push(newUser);\r\n    renderUsers();\r\n    updateKpis();\r\n    closeUserModal();\r\n    syncUserToBackend(newUser);\r\n    await loadUserListFromDb();\r\n  });\r\n"
if old not in text:
    raise SystemExit("old block not found")
text = text.replace(old, new, 1)
path.write_bytes(text)
